title: Rohan Sarkar
description: Senior Android Engineer · Mobile Architect | Fintech & Scalable Systems
theme: minima

author:
  name: Rohan Sarkar
  email: rohaneeiitr@gmail.com
  linkedin: https://www.linkedin.com/in/rohan-sarkar-b5b20b64/
  github: https://github.com/rohaniitr

show_excerpts: false
